# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 7
POST_CONTENT_ON_HOMEPAGE = False
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$vR683aIW$e000a816bd06db87dd06c60365ee61d4b052e96f'
ANALYTICS_ID = ''
SQLALCHEMY_DATABASE_URI = 'sqlite:///simple.db'
GITHUB_USERNAME = 'Z1MM32M4N'
CONTACT_EMAIL = 'zimmerman.jake@gmail.com'
BLOG_TITLE = 'On Hard Work and No Sleep'
BLOG_TAGLINE = ''
BLOG_URL = '/'
FONT_NAME = 'Droid+Serif'
SECRET_KEY = '2L4WPGC6MPLGWDWDS3BHAO4JSJP4CES7YJSDX3CWP2DW3FD2NMBA===='
DISQUS_SHORTNAME = 'jake'
USE_ADDTOANY = True
USE_SUBTOME = False
